source 'https://rubygems.org'

gem 'rails', '3.2.1'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'haml'
gem 'formtastic'
gem 'paperclip'
gem 'will_paginate'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'enumerated_attribute'

# authlogic doesn't have enough built-in magic
gem 'devise'
